version: '3.8'
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://root:example@db:27017/marketplace?authSource=admin
    networks:
      - netapi
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - netapi
  
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
    networks:
      - netapi
    volumes:
      - mongo-data:/data/db
  
networks:
  netapi:
    external: true
    
volumes:
  mongo-data: 